### ISSUE TITLE
combine_lists() should put scalar values in lists

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1172]
Currently, we have to do this:

```yaml
runners:
  emr:
    setup:
    - /run/one/command
```

and it would be reasonable to allow:

```yaml
runners:
  emr:
    setup: /run/one/command
```
