### ISSUE TITLE
Capture output printed via System.out.println

### ISSUE THREAD

**Issue by marklit** [Yelp/mrjob#1202]
I am trying to run the pi estimation example shipped with Hadoop on EMR. The jar file executes but it's output written via [System.out.println](https://github.com/apache/hadoop/blob/3b85bd7c3391719624a261f061a67cc4356be477/hadoop-mapreduce-project/hadoop-mapreduce-examples/src/main/java/org/apache/hadoop/examples/QuasiMonteCarlo.java#L358-L359) (lines 358 & 359) don't appear anywhere in the output given by mrjob nor are they to be found anywhere in the S3 bucket output.

Here are the steps I took to run the job:

Got a copy of the examples jar:

```bash
$ curl -O http://www.eu.apache.org/dist/hadoop/common/hadoop-2.6.3/hadoop-2.6.3.tar.gz
$ tar zxf hadoop-2.6.3.tar.gz
$ cp hadoop-2.6.3/share/hadoop/mapreduce/hadoop-mapreduce-examples-2.6.3.jar ./
```

Created an `mrjob.conf` file:

```yaml
runners:
  emr:
    aws_region: us-east-1
    ec2_master_instance_type: c3.xlarge
    ec2_master_instance_bid_price: '0.05'
    ec2_instance_type: c3.xlarge
    ec2_core_instance_bid_price: '0.05'
    num_ec2_instances: 2
    ami_version: 3.6.0
```

Created a job:

```python
from mrjob.job import MRJob
from mrjob.step import JarStep


class CalcPiJob(MRJob):

    def steps(self):
        return [JarStep(
            jar='hadoop-mapreduce-examples.jar',
            args=['pi', 10, 100000])]


if __name__ == '__main__':
    CalcPiJob.run()
```

Created an empty input file:

```bash
$ touch none
```

Ran the job:

```bash
$ python calc_pi_job.py -r emr --conf-path mrjob.conf --output-dir s3://<my throwaway bucket>/test1/ none
...
Job completed.
Running time was 74.0s (not counting time spent waiting for the EC2 instances)
ec2_key_pair_file not specified, going to S3
...
Streaming final output from s3://<my throwaway bucket>/test1/
...
```

The bucket does exist but the new `test1` wasn't created.

I looked through the S3 bucket contents for the mrjob logs but I couldn't find '3.14' anywhere:

```bash
$ s3cmd get --recursive s3://mrjob-blah/logs/j-blah
$ cd j-blah
$ find . -type f -name '*.gz' -exec gunzip "{}" \;
$ grep -r '3.14' * | wc -l
0
```

The output usually looks something like:

```
Estimated value of Pi is 3.14158440000000000000
```

Any idea how I can capture this output?
