### ISSUE TITLE
don't disable bootstrap_python_packages on 2.x AMIs

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1263]
Yelp appears to use `bootstrap_python_packages` pretty extensively, and has gotten it to work on Debian squeeze by updating `sources.list`:

```yaml
runners:
  emr:
    bootstrap:
      - (sudo bash -c 'grep -q ^6 /etc/debian_version && echo "deb http://archive.debian.org/debian/ squeeze main contrib non-free" > /etc/apt/sources.list')
```

This option is already broken on 2.x AMIs (by Debian), but if someone has found a way to make it work, we shouldn't break it further. Just issuing a warning, similar to what we do when people try to use Python 3 on AMIs before 3.7.0 (essentially, this probably won't work, but we'll give it a try) should be good enough.

This undoes #1248.
