### ISSUE TITLE
emr_configurations option

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1276]
mrjob should directly support the [Configurations](http://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-configure-apps.html) API parameter for 4.x AMIs. Similar to `additional_emr_info`, it should take a string or a JSON-able data structure (in this case, a list, not a dictionary).

See [this mrjob Google Group thread](https://groups.google.com/forum/#!topic/mrjob/Avi7kiH8SgQ) for an example.

**Comment by davidmarin** [comment]
Ugh, this is just ridiculous to support using the old (XML-based) call format that `boto` uses.

Basically, I'd have to serialize the configuration data structure, and then *de*-serialize it to match configs for pooling.

This is going to have to wait for #1304 (replace `boto` with `boto3`). In the meantime, you'll be able to do this in mrjob 0.5.2:

```yaml
runners:
  emr:
    api_params:
      Configurations:
      - Classification: hadoop-env
        Configurations:
        - Classification: export
          Properties:
            HADOOP_CLASSPATH: /path/to/my.jar
            HADOOP_USER_CLASSPATH_FIRST: 'true'
        Properties: {}
```

**Comment by davidmarin** [comment]
Going to give this another shot with `boto` before giving up until `boto3` (see #1304).

**Comment by davidmarin** [comment]
This works:

```yaml
runners:
  emr:
    emr_api_params:
      Configurations.member.1.Classification: "core-site"
```

**Comment by davidmarin** [comment]
Aha, was *almost* there. The trick is you have to encode `Properties` as a list of `KeyValue`\s. This works:

```yaml
runners:
  emr:
    emr_api_params:
      Configurations.member.1.Classification: core-site
      Configurations.member.1.Properties.member.1.Key: foo
      Configurations.member.1.Properties.member.1.Value: bar
```
