### ISSUE TITLE
Task Instances in EMR are idle and not processing jobs

### ISSUE THREAD

**Issue by zbagz** [Yelp/mrjob#1352]
Hello, I'm trying to work with my first dataset (common crawl), but it's not working out for me. Basically, all my task instances are idleing, the only one apparently working is the core instance. I've checked this connecting to these instances via SSH, ps aux and python wasn't even running - 100% idle on top command . I also checked dmesg for out of memory kernel errors but nothing showed up.

My code does work in local mode, and also it works on EMR with a different config file (mostly default settings 1 - instance only - I think it's: m1.medium) on a very small subset (5 lines only). 

However, when I run my "production" config, it gives no error, and shows up as "running", but progress doesn't change.

[http://i.imgur.com/xVdgT6I.png](http://i.imgur.com/xVdgT6I.png)
[http://i.imgur.com/UUMZL2e.png](http://i.imgur.com/UUMZL2e.png)

This is my mrjob.conf

```
runners:
  emr:
    aws_region: us-east-1
    aws_access_key_id: key_id
    aws_secret_access_key: access_key

    emr_api_params:
        Instances.Ec2SubnetId: subnet-xxxxxxxx

    ec2_key_pair: emr
    ec2_key_pair_file: ~/.ssh/emr.pem
    ssh_tunnel_to_job_tracker: true

    ec2_master_instance_type: 'm1.medium'

    ec2_core_instance_type: 'm4.xlarge'
    num_ec2_core_instances: 1

    ec2_task_instance_type: 'c4.8xlarge'
    ec2_task_instance_bid_price: '0.4'
    num_ec2_task_instances: 20

    # EMR comes with Python 2.6 by default -- installing Python 2.7 takes a while but might be necessary
    # We also install packages needed for streaming compressed files from S3 or reading WARC files
    # There's a newer AMI version but it has issues with the released stable mrjob
    ami_version: 3.0.4
    interpreter: python2.7
    bootstrap:
      - sudo yum --releasever=2014.09 install -y python27 python27-devel gcc-c++
      - sudo python2.7 get-pip.py#
      - sudo pip2.7 install boto mrjob simplejson warc
      - sudo pip2.7 install https://github.com/commoncrawl/gzipstream/archive/master.zip
      - sudo pip2.7 install tldextract
```

I've been also checking the logs but I couldn't find anything suspicious... well maybe it's just me. I can upload the whole folder if you guys want to take a look. 

I really think it's something else related to my instances config because when running on emr with default settings (only 1 master node) it works just fine.

I don't know if this setup is overkill or just ok. I've already wasted around $100 trying to get this working with no luck... well I guess that is the cost for a beginner. My job is just extracting urls with a simple regex, extracting domain from url with tldextract and removing duplicates. I'm trying to run this against 2 common crawl datasets.

Well I'm out of ideas at the moment...

Thank you everyone.
