### ISSUE TITLE
specify EBS volumes when creating cluster

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1357]
EBS volumes are a new-ish thing we can configure on `InstanceGroups` (see http://docs.aws.amazon.com/ElasticMapReduce/latest/ManagementGuide/emr-storage-ebs.html).

Unfortunately, the way we currently specify instance groups is pretty well entangled with `boto.emr.instance_group.InstanceGroup`, which is unlikely to ever be updated. Really, mrjob needs to move to `boto3` first (see #1304).

**Comment by jimjh** [comment]
While waiting for mrjob to use boto3, here's a workaround!

```yml
      Instances.MasterInstanceType: ~
      Instances.SlaveInstanceType: ~
      Instances.InstanceCount: ~

      # configure EBS for master
      Instances.InstanceGroups.member.1.InstanceCount: 1
      Instances.InstanceGroups.member.1.InstanceRole: MASTER
      Instances.InstanceGroups.member.1.InstanceType: m4.xlarge
      Instances.InstanceGroups.member.1.Name: master
      Instances.InstanceGroups.member.1.EbsConfiguration.EbsBlockDeviceConfigs.member.1.VolumeSpecification.SizeInGB: 10
      Instances.InstanceGroups.member.1.EbsConfiguration.EbsBlockDeviceConfigs.member.1.VolumeSpecification.VolumeType: gp2
      Instances.InstanceGroups.member.1.EbsConfiguration.EbsBlockDeviceConfigs.member.1.VolumesPerInstance: 1
      Instances.InstanceGroups.member.1.EbsConfiguration.EbsOptimized: 'true'
      # configure EBS for core
      Instances.InstanceGroups.member.2.InstanceCount: 2
      Instances.InstanceGroups.member.2.InstanceRole: CORE
      Instances.InstanceGroups.member.2.InstanceType: r3.xlarge
      Instances.InstanceGroups.member.2.Name: core
      Instances.InstanceGroups.member.2.EbsConfiguration.EbsBlockDeviceConfigs.member.1.VolumeSpecification.SizeInGB: 10
      Instances.InstanceGroups.member.2.EbsConfiguration.EbsBlockDeviceConfigs.member.1.VolumeSpecification.VolumeType: gp2
      Instances.InstanceGroups.member.2.EbsConfiguration.EbsBlockDeviceConfigs.member.1.VolumesPerInstance: 2
      Instances.InstanceGroups.member.2.EbsConfiguration.EbsOptimized: 'true'
```

Obviously, this is brittle.

**Comment by mirth** [comment]
@jimjh tell please where should i put these lines?

**Comment by jimjh** [comment]
```yml
runners:
  emr:
    emr_api_params:
      # <here>
```
