### ISSUE TITLE
switching from c3.xlarge to c4.xlarge instance type is adding extraneous EBS volume

### ISSUE THREAD

**Issue by j4y** [Yelp/mrjob#1527]
I'm running an EMR job and when I change from c3.xlarge to c4.xlarge instance types there is an extra EBS volume added.  It turns out to be a 32 GB disk and amazon has limits on the amount of EBS storage you can use.

Any idea how to configure the job so that it doesn't add this volume?

This is what I tried but it failed with a validation error:
```
runners:
  emr:
    emr_api_params:
        Instances.Ec2SubnetId: subnet-xxxxxx
        # configure EBS for core
        Instances.InstanceGroups.member.2.VolumesPerInstance: 0
```
