### ISSUE TITLE
Can not override emr_configurations in multiple conf files

### ISSUE THREAD

**Issue by mgmarino** [Yelp/mrjob#2097]
Currently, if you have two conf files e.g.;

File 1:
```yaml
runners:
  emr:
    ...
    emr_configurations:
    - Classification: spark-defaults
      Properties:
        spark.executor.memory: 28G
        spark.executor.cores: "4"
        spark.driver.memory: 24G
        spark.driver.cores: "5"
        spark.sql.files.openCostInBytes: "4194304000"
        spark.sql.shuffle.partitions: "10000"
        spark.yarn.maxAppAttempts: "1"
    - Classification: hive-site
      Properties:
        hive.metastore.client.factory.class: com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory
```

File 2:

```yaml
runners:
  emr:
    ...
    emr_configurations:
    - Classification: spark-defaults
      Properties:
        spark.executor.memory: 2G
```

this will fail with an API error:

```
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the RunJobFlow operation: Classification 'spark-defaults' was specified multiple times.
```

This is because the lists are simply concatenated (as specified correctly in the documents).  Adding a `!clear` to the File 2 does not work, and rather results in the error:

```bash
  File "/Users/.../.local/share/virtualenvs/.../lib/python3.6/site-packages/mrjob/emr.py", line 505, in _fix_opt
    return [_fix_configuration_opt(c) for c in opt_value]
TypeError: 'ClearedValue' object is not iterable
```
It wasn't clear to me if this is expected from the documentation.  

I see a few possible solutions to this:

1. Allow the values to be cleared.
1. Only take the most recent `emr_configurations`, similar to how the instance variables are handled.  (See e.g. `_combine_opts` and `_blank_out_conflicting_opts` in https://github.com/Yelp/mrjob/blob/master/mrjob/emr.py#L458)
1. Combine `emr_configurations` by combining dictionaries with the same Classification.  

Of these, I think 
   - 3 is the most desirable (but possibly the most difficult to support), 
   - 1 is fairly simply, but makes it impossible to combine `emr_configurations` that have the same Classification.
   - 2 is heavy-handed and could break user code, but could be a one-line change.  

Both 1 and 3 should be backwards compatible.  I'm happy to look at fixing this and providing a PR, but would like input first?
