### ISSUE TITLE
fix booleans in jobconf in mrjob.conf

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#323]
`"true"` and `"false"` are pretty common jobconf values, but if you do something like this:

``` yaml
runners:
 emr:
   jobconf:
     mapred.output.compress: true
     mapred.output.compression.codec: org.apache.hadoop.io.compress.GzipCodec
```

The `true` gets converted to `True` (Python constant), which then gets passed to Hadoop as the string `True` (uppercase), which Hadoop then interprets as false because `"True" != "true"`.

The correct thing to do is put the `true` in quotes:

``` yaml
runners:
 emr:
   jobconf:
     mapred.output.compress: 'true'
     mapred.output.compression.codec: org.apache.hadoop.io.compress.GzipCodec
```

We should catch cases like this, convert the booleans to the appropriate lowercase strings, and issue a warning about the correct way to represent them in YAML.

We should probably do this for numbers too, though there's less chance they'll get converted to a form Hadoop doesn't understand.
