### ISSUE TITLE
runners/all config subsection

### ISSUE THREAD

**Issue by irskep** [Yelp/mrjob#417]
If you want to duplicate options across runners (e.g. `local` and `hadoop`, for simulation purposes), you currently have to use some YAML magic. I'd like to see this as well:

``` yaml
runners:
  all:
    python_bin: python3.2
```

With the way `load_opts_from_mrjob_conf()` works now, this is very easy to add.
