### ISSUE TITLE
aws_connection_settings option

### ISSUE THREAD

**Issue by irskep** [Yelp/mrjob#512]
`boto` cannot connect to buckets with dots in their names unless you are not using SSL. The `is_secure` parameter to connection objects turns of SSL.

I don't want to add a new parameter for every `boto` option we don't deal with, but we could do this instead:

``` yaml
runners:
  emr:
    aws_connection_settings: {'is_secure': false}
```
