### ISSUE TITLE
Misleading example for jobconf option in cookbook

### ISSUE THREAD

**Issue by inbergo** [Yelp/mrjob#710]
Example in _Increasing the task timeout_ part of [Cookbook](https://github.com/Yelp/mrjob/blob/master/docs/guides/cookbook.rst) is misleading:

```
runners:
    hadoop: # this will work for both hadoop and emr
        jobconf:
            mapred.task.timeout: 3600000
```

puts jobconf in runners section of _opts dictionary, from where it will never be found by `MRJobRunner._hadoop_conf_args()`. So it seems that either docs or mentioned procedure should be changed.
