### ISSUE TITLE
Create empty shared dirs with #<name>/

### ISSUE THREAD

**Issue by coyotemarin** [Yelp/mrjob#801]
I'd like to enable using virtualenvs on Hadoop, with a setup script something like this:

``` yaml:
runners:
  hadoop:
    setup:
    - cd #shared/
    - if [ ! -e venv ]; then virtualenv venv; fi
    - . venv/bin/activate
    - pip install -r requirements.txt#
```

This way, when multiple tasks run on the same node, only one would have to set up the virtualenv, and the others could just use it.

Basically, for every file/archive with a name but no path, we create a unique empty file/archive and upload that to Hadoop.

We should require at least a path or a name; `#/` and plain old `#` shouldn't be allowed (the latter would make it impossible to comment, which my gut tells me is a bad idea).
