### ISSUE TITLE
max_hours_idle in mrjob v4.3.0-dev  behave like (max_working_hour -1 )

### ISSUE THREAD

**Issue by William-Sang** [Yelp/mrjob#941]
max_hours_idle  
in doc:
```
If we create a persistent job flow, have it automatically terminate itself after it’s been idle this many hours AND we’re within mins_to_end_of_hour of an EC2 billing hour.
```
 
but it actually behave like:  max_hours_idle + 1  = max_working_hour
It really confused me.
I set max_hours_idle = 1, then run many same jobs sequentially( say it will run forever). But when time run close to 2 hours, no matter whether current job is done or not, it will teminated current job, and restart a new cluster to continue preview not-finished job. then repeat it when it come close to 2 hours.

anyone have such experience?

below is my mrjob.conf:

```
runners:
    emr:
        setup:
        - export PYTHONPATH=$PYTHONPATH:source.tar.gz#/
        aws_access_key_id: xxxxxxxxx
        aws_region: ap-northeast-1
        aws_secret_access_key:xxxxxxxxx
        ami_version: 3.1.0
        num_ec2_core_instances: 10
        ec2_core_instance_type: m3.xlarge
        ec2_master_instance_type: m1.large
        enable_emr_debugging: True
        s3_log_uri: s3://xxxxx/logs/
        jobconf:
            # "true" must be a string argument, not a boolean! (#323)
            mapreduce.output.fileoutputformat.compress: "true"
            mapreduce.output.fileoutputformat.compress.codec : org.apache.hadoop.io.compress.BZip2Codec
        python_archives:
        - source.tar.gz
        cleanup: NONE
        pool_emr_job_flows: "true"
        max_hours_idle: 1
        pool_wait_minutes: 5
        ec2_key_pair: emr
        ec2_key_pair_file: /ssh/emr.pem # ~/ and $ENV_VARS allowed here
        ssh_tunnel_to_job_tracker: true
```
